# Generated by Django 5.1.6 on 2026-02-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_meterpoint_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterPointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('reading_date', models.DateField()),
                ('consumption_kwh', models.PositiveIntegerField()),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=8)),
                ('meter_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_items', to='portal.meterpoint')),
            ],
            options={
                'ordering': ['period_start'],
                'unique_together': {('meter_point', 'period_start')},
            },
        ),
    ]
