# Generated by Django 5.1.6 on 2026-02-20 09:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_meterpointhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='fixed_unit_price_eur_kwh',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.2850'), max_digits=6),
        ),
        migrations.AddField(
            model_name='contract',
            name='standing_charge_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='contract',
            name='tariff_type',
            field=models.CharField(choices=[('fixed', 'Fixe'), ('variable', 'Variable')], default='fixed', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='consumption_kwh',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='standing_charge_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price_eur_kwh',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6),
        ),
    ]
